on:
  push:
    branches:
      - main
  pull_request:

jobs:
  verify:
    name: Verify files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Test Tailwind
        working-directory: test
        run: |
          npm install
          npm run lint
          npm run build
